import type {
  AdminActivity,
  AdminActivityPoint,
  AdminSettings,
  AdminStat,
  AdminUser,
  SystemServiceStatus,
} from "./types";

export const adminProfile = {
  name: "Nguyen Anh Minh",
  role: "Quản trị hệ thống",
  email: "admin@academishare.vn",
  avatarUrl:
    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=160&q=80",
} as const;

export const adminStats: AdminStat[] = [
  {
    label: "Tổng người dùng",
    value: "12,840",
    caption: "1,284 người dùng mới trong tháng",
    icon: "group",
    tone: "primary",
    trend: "+12%",
  },
  {
    label: "Phiên hoạt động",
    value: "567",
    caption: "82 phiên đang học với AI",
    icon: "bolt",
    tone: "secondary",
    trend: "+8%",
  },
  {
    label: "Sức khỏe hệ thống",
    value: "98.7%",
    caption: "4 dịch vụ vận hành ổn định",
    icon: "monitoring",
    tone: "tertiary",
    trend: "Tốt",
  },
  {
    label: "Giao dịch tài liệu",
    value: "42,318",
    caption: "Tải lên, tải xuống và chia sẻ",
    icon: "sync_alt",
    tone: "neutral",
    trend: "+18%",
  },
];

export const activityTimeline: AdminActivityPoint[] = [
  { label: "T2", users: 72, sessions: 44, transactions: 61 },
  { label: "T3", users: 86, sessions: 58, transactions: 74 },
  { label: "T4", users: 64, sessions: 42, transactions: 52 },
  { label: "T5", users: 98, sessions: 71, transactions: 89 },
  { label: "T6", users: 81, sessions: 65, transactions: 78 },
  { label: "T7", users: 55, sessions: 39, transactions: 48 },
  { label: "CN", users: 46, sessions: 32, transactions: 41 },
];

export const recentAdminActivities: AdminActivity[] = [
  {
    id: "act-001",
    action: "Cập nhật chính sách bảo mật",
    performer: "Nguyen Anh Minh",
    timestamp: "10 phút trước",
    details: "Bật yêu cầu 2FA cho nhóm quản trị.",
    tone: "primary",
  },
  {
    id: "act-002",
    action: "Tạm khóa tài khoản",
    performer: "Tran Bao Long",
    timestamp: "28 phút trước",
    details: "Tài khoản USR-1008 bị khóa do đăng nhập bất thường.",
    tone: "error",
  },
  {
    id: "act-003",
    action: "Duyệt vai trò kiểm duyệt viên",
    performer: "Le Thu Ha",
    timestamp: "46 phút trước",
    details: "Cấp quyền kiểm duyệt tài liệu cho 2 tài khoản.",
    tone: "secondary",
  },
  {
    id: "act-004",
    action: "Hệ thống sao lưu hoàn tất",
    performer: "System Scheduler",
    timestamp: "1 giờ trước",
    details: "Backup dữ liệu học liệu hoàn tất trong 12 phút.",
    tone: "tertiary",
  },
];

export const systemServices: SystemServiceStatus[] = [
  {
    name: "API xác thực",
    status: "operational",
    uptime: "99.99%",
    latency: "42ms",
  },
  {
    name: "Kho lưu trữ tài liệu",
    status: "operational",
    uptime: "99.95%",
    latency: "88ms",
  },
  {
    name: "Trợ lý AI",
    status: "degraded",
    uptime: "98.21%",
    latency: "240ms",
  },
  {
    name: "Dịch vụ email",
    status: "maintenance",
    uptime: "97.84%",
    latency: "120ms",
  },
];

export const mockUsers: AdminUser[] = [
  {
    id: "USR-1001",
    name: "Nguyen Minh Quan",
    email: "quan.nguyen@hcmut.edu.vn",
    role: "ADMIN",
    status: "ACTIVE",
    createdAt: "12/01/2026",
    lastLogin: "26/05/2026 08:32",
  },
  {
    id: "USR-1002",
    name: "Tran Thi Bich Ngoc",
    email: "ngoc.tran@uit.edu.vn",
    role: "MODERATOR",
    status: "ACTIVE",
    createdAt: "18/01/2026",
    lastLogin: "26/05/2026 07:48",
  },
  {
    id: "USR-1003",
    name: "Le Hoang Nam",
    email: "nam.le@student.edu.vn",
    role: "USER",
    status: "ACTIVE",
    createdAt: "22/01/2026",
    lastLogin: "25/05/2026 21:14",
  },
  {
    id: "USR-1004",
    name: "Pham Thu Thao",
    email: "thao.pham@uel.edu.vn",
    role: "USER",
    status: "UNVERIFIED",
    createdAt: "03/02/2026",
    lastLogin: "18/05/2026 10:06",
  },
  {
    id: "USR-1005",
    name: "Do Gia Huy",
    email: "huy.do@neu.edu.vn",
    role: "MODERATOR",
    status: "ACTIVE",
    createdAt: "08/02/2026",
    lastLogin: "26/05/2026 09:10",
  },
  {
    id: "USR-1006",
    name: "Vo Anh Khoa",
    email: "khoa.vo@hust.edu.vn",
    role: "USER",
    status: "UNVERIFIED",
    createdAt: "15/02/2026",
    lastLogin: "02/05/2026 12:40",
  },
  {
    id: "USR-1007",
    name: "Bui Minh Chau",
    email: "chau.bui@ftu.edu.vn",
    role: "USER",
    status: "ACTIVE",
    createdAt: "21/02/2026",
    lastLogin: "25/05/2026 19:55",
  },
  {
    id: "USR-1008",
    name: "Dang Thanh Son",
    email: "son.dang@student.edu.vn",
    role: "USER",
    status: "BANNED",
    createdAt: "26/02/2026",
    lastLogin: "20/05/2026 16:22",
  },
  {
    id: "USR-1009",
    name: "Hoang Yen Nhi",
    email: "nhi.hoang@vnu.edu.vn",
    role: "ADMIN",
    status: "ACTIVE",
    createdAt: "02/03/2026",
    lastLogin: "26/05/2026 08:02",
  },
  {
    id: "USR-1010",
    name: "Mai Duc Anh",
    email: "anh.mai@ueh.edu.vn",
    role: "USER",
    status: "ACTIVE",
    createdAt: "10/03/2026",
    lastLogin: "24/05/2026 15:34",
  },
  {
    id: "USR-1011",
    name: "Nguyen Ha Linh",
    email: "linh.nguyen@hanu.edu.vn",
    role: "USER",
    status: "ACTIVE",
    createdAt: "14/03/2026",
    lastLogin: "23/05/2026 11:08",
  },
  {
    id: "USR-1012",
    name: "Tran Bao Long",
    email: "long.tran@hcmus.edu.vn",
    role: "USER",
    status: "BANNED",
    createdAt: "19/03/2026",
    lastLogin: "21/05/2026 20:12",
  },
  {
    id: "USR-1013",
    name: "Le Thu Ha",
    email: "ha.le@ussh.edu.vn",
    role: "MODERATOR",
    status: "ACTIVE",
    createdAt: "25/03/2026",
    lastLogin: "26/05/2026 06:45",
  },
  {
    id: "USR-1014",
    name: "Pham Quoc Viet",
    email: "viet.pham@ctu.edu.vn",
    role: "USER",
    status: "UNVERIFIED",
    createdAt: "31/03/2026",
    lastLogin: "12/05/2026 09:18",
  },
  {
    id: "USR-1015",
    name: "Do Khanh Vy",
    email: "vy.do@dlu.edu.vn",
    role: "USER",
    status: "ACTIVE",
    createdAt: "06/04/2026",
    lastLogin: "25/05/2026 22:02",
  },
  {
    id: "USR-1016",
    name: "Vo Minh Tri",
    email: "tri.vo@student.edu.vn",
    role: "USER",
    status: "ACTIVE",
    createdAt: "12/04/2026",
    lastLogin: "24/05/2026 07:56",
  },
  {
    id: "USR-1017",
    name: "Bui Gia Bao",
    email: "bao.bui@hueuni.edu.vn",
    role: "USER",
    status: "UNVERIFIED",
    createdAt: "19/04/2026",
    lastLogin: "08/05/2026 14:20",
  },
  {
    id: "USR-1018",
    name: "Dang My Duyen",
    email: "duyen.dang@tdtu.edu.vn",
    role: "MODERATOR",
    status: "ACTIVE",
    createdAt: "25/04/2026",
    lastLogin: "26/05/2026 09:35",
  },
];

export const mockSettings: AdminSettings = {
  general: {
    systemName: "AcademiShare",
    systemLogo: "AS",
    systemDescription:
      "Nền tảng chia sẻ tài liệu học thuật và cộng đồng học tập dành cho sinh viên.",
    timezone: "Asia/Ho_Chi_Minh",
  },
  security: {
    passwordMinLength: 10,
    passwordExpiry: 90,
    twoFAEnabled: true,
    sessionTimeout: 45,
  },
  email: {
    smtpServer: "smtp.academishare.vn",
    smtpPort: 587,
    senderEmail: "noreply@academishare.vn",
    senderName: "AcademiShare System",
  },
  notifications: {
    emailAlerts: true,
    systemAlerts: true,
    alertFrequency: "Ngay lập tức",
  },
};
